// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClTsXp0w1EigDVdzaxUNnTu8BDOGc2Zb4',
    appId: '1:323337862734:web:6d806c94b4a6133f26cd1f',
    messagingSenderId: '323337862734',
    projectId: 'streaming-dart',
    authDomain: 'streaming-dart.firebaseapp.com',
    storageBucket: 'streaming-dart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxRRHvMJgQ3ybENnQfVvOHqtCuhQfjiKY',
    appId: '1:323337862734:android:d3b41cd439ab943126cd1f',
    messagingSenderId: '323337862734',
    projectId: 'streaming-dart',
    storageBucket: 'streaming-dart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMveCuWVImspL3PTTcvro5kTxvs6TdUew',
    appId: '1:323337862734:ios:86f8809171df5ab626cd1f',
    messagingSenderId: '323337862734',
    projectId: 'streaming-dart',
    storageBucket: 'streaming-dart.appspot.com',
    iosClientId: '323337862734-uvcjinshq0icniap0e2skjco23hqq0sc.apps.googleusercontent.com',
    iosBundleId: 'com.example.streamingApp',
  );
}
